# Generated by Django 4.2.7 on 2026-06-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_id', models.IntegerField()),
                ('livre_id', models.IntegerField()),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateTimeField()),
                ('date_retour_effective', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('retourne', 'Retourné'), ('en_retard', 'En retard')], default='en_cours', max_length=20)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'emprunts',
                'ordering': ['-date_emprunt'],
            },
        ),
    ]
