# Generated by Django 4.2.7 on 2026-06-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('editeur', models.CharField(blank=True, max_length=255)),
                ('annee_publication', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('nombre_exemplaires', models.IntegerField(default=1)),
                ('exemplaires_disponibles', models.IntegerField(default=1)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'livres',
                'ordering': ['titre'],
            },
        ),
    ]
